# Generated by Django 4.2.8 on 2026-05-08 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario_proveedores_administracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudrepuestodetalle',
            name='cantidad_recibida_taller',
            field=models.IntegerField(default=0, verbose_name='cantidad recibida en taller'),
        ),
        migrations.AddField(
            model_name='solicitudrepuestodetalle',
            name='recibido_taller_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='recibido en taller en'),
        ),
        migrations.AddField(
            model_name='solicitudrepuestodetalle',
            name='recibido_taller_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_repuesto_recibidas_taller', to=settings.AUTH_USER_MODEL, verbose_name='recibido en taller por'),
        ),
    ]
