# Generated by Django 4.2.8 on 2026-05-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_proveedores_administracion', '0002_solicitudrepuestodetalle_cantidad_recibida_taller_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagotaller',
            name='ambiente',
            field=models.CharField(db_index=True, default='PRUEBA_REAL', max_length=20, verbose_name='ambiente'),
        ),
        migrations.AddField(
            model_name='pagotaller',
            name='callback_intentos',
            field=models.IntegerField(default=0, verbose_name='intentos callback'),
        ),
        migrations.AddField(
            model_name='pagotaller',
            name='callback_ultimo_hash',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='callback hash'),
        ),
        migrations.AddField(
            model_name='pagotaller',
            name='codigo_pago',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='codigo pago'),
        ),
        migrations.AddField(
            model_name='pagotaller',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='descripcion'),
        ),
        migrations.AddField(
            model_name='pagotaller',
            name='fecha_expiracion',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='fecha expiracion'),
        ),
        migrations.AddField(
            model_name='pagotaller',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha pago'),
        ),
        migrations.AddField(
            model_name='pagotaller',
            name='id_destino',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='id destino'),
        ),
        migrations.AddField(
            model_name='pagotaller',
            name='id_pago_proveedor',
            field=models.CharField(blank=True, db_index=True, max_length=120, null=True, verbose_name='id pago proveedor'),
        ),
        migrations.AddField(
            model_name='pagotaller',
            name='id_transaccion_proveedor',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='id transaccion proveedor'),
        ),
        migrations.AddField(
            model_name='pagotaller',
            name='metadata',
            field=models.JSONField(blank=True, null=True, verbose_name='metadata'),
        ),
        migrations.AddField(
            model_name='pagotaller',
            name='monto_cobrado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='monto cobrado'),
        ),
        migrations.AddField(
            model_name='pagotaller',
            name='monto_pagado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='monto pagado'),
        ),
        migrations.AddField(
            model_name='pagotaller',
            name='monto_real',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='monto real'),
        ),
        migrations.AddField(
            model_name='pagotaller',
            name='proveedor',
            field=models.CharField(db_index=True, default='LIBELULA_QR', max_length=32, verbose_name='proveedor'),
        ),
        migrations.AddField(
            model_name='pagotaller',
            name='qr_imagen_base64',
            field=models.TextField(blank=True, null=True, verbose_name='qr imagen base64'),
        ),
        migrations.AddField(
            model_name='pagotaller',
            name='qr_imagen_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='qr imagen url'),
        ),
        migrations.AddField(
            model_name='pagotaller',
            name='qr_payload',
            field=models.JSONField(blank=True, null=True, verbose_name='qr payload'),
        ),
        migrations.AddField(
            model_name='pagotaller',
            name='referencia_externa',
            field=models.CharField(blank=True, db_index=True, max_length=120, null=True, verbose_name='referencia externa'),
        ),
        migrations.AddField(
            model_name='pagotaller',
            name='respuesta_proveedor_raw',
            field=models.JSONField(blank=True, null=True, verbose_name='respuesta proveedor raw'),
        ),
        migrations.AddField(
            model_name='pagotaller',
            name='tipo_destino',
            field=models.CharField(db_index=True, default='CITA', max_length=40, verbose_name='tipo destino'),
        ),
        migrations.AddField(
            model_name='pagotaller',
            name='url_pago',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='url pago'),
        ),
        migrations.AlterField(
            model_name='pagotaller',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADO', 'Confirmado'), ('FALLIDO', 'Fallido'), ('VENCIDO', 'Vencido'), ('CANCELADO', 'Cancelado'), ('PROCESANDO', 'Procesando'), ('RECHAZADO', 'Rechazado'), ('MONTO_INCORRECTO', 'Monto incorrecto'), ('ERROR', 'Error'), ('FACTURADO', 'Facturado'), ('REGISTRADO', 'Registrado'), ('RECIBIDO', 'Recibido'), ('ANULADO', 'Anulado')], db_index=True, default='PENDIENTE', max_length=20, verbose_name='estado'),
        ),
    ]
