# Generated by Django 4.2.8 on 2026-03-08 03:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        help_text="Email único dentro de la empresa (no bloqueado globalmente)",
                        max_length=255,
                        verbose_name="email",
                    ),
                ),
                ("nombres", models.CharField(max_length=255, verbose_name="nombres")),
                (
                    "apellidos",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="apellidos"
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="teléfono"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Designa si el usuario puede iniciar sesión",
                        verbose_name="activo",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado en"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado en"),
                ),
            ],
            options={
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
                "db_table": "usuarios",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Auditoria",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "accion",
                    models.CharField(
                        db_index=True,
                        help_text="Tipo de acción (crear, actualizar, eliminar, login, etc)",
                        max_length=100,
                        verbose_name="acción",
                    ),
                ),
                (
                    "entidad_tipo",
                    models.CharField(
                        blank=True,
                        help_text="Modelo sobre el que se actuó (Usuario, Empresa, etc)",
                        max_length=100,
                        null=True,
                        verbose_name="tipo de entidad",
                    ),
                ),
                (
                    "entidad_id",
                    models.UUIDField(
                        blank=True,
                        help_text="UUID de la entidad modificada",
                        null=True,
                        verbose_name="ID de entidad",
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(
                        blank=True,
                        help_text="Descripción legible de la acción",
                        max_length=500,
                        null=True,
                        verbose_name="descripción",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        default=dict,
                        help_text="Datos adicionales en JSON (cambios, valores antiguos, etc)",
                        verbose_name="metadata",
                    ),
                ),
                (
                    "ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP desde donde se realizó la acción",
                        null=True,
                        verbose_name="IP",
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True,
                        help_text="User-Agent del cliente",
                        max_length=500,
                        null=True,
                        verbose_name="user agent",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="creado en"
                    ),
                ),
            ],
            options={
                "verbose_name": "Auditoría",
                "verbose_name_plural": "Auditorías",
                "db_table": "auditoria",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre legal de la empresa",
                        max_length=255,
                        verbose_name="nombre",
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        db_index=True,
                        help_text="Identificador único para URL (ej: acme, globex)",
                        max_length=255,
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[("ACTIVA", "Activa"), ("INACTIVA", "Inactiva")],
                        db_index=True,
                        default="ACTIVA",
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                (
                    "suscripcion_hasta",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha de vencimiento de la suscripción actual",
                        null=True,
                        verbose_name="suscripción hasta",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado en"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado en"),
                ),
            ],
            options={
                "verbose_name": "Empresa",
                "verbose_name_plural": "Empresas",
                "db_table": "empresas",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        db_index=True,
                        help_text="Código único del plan (ej: STARTER, PRO, ENTERPRISE)",
                        max_length=100,
                        unique=True,
                        verbose_name="código",
                    ),
                ),
                ("nombre", models.CharField(max_length=255, verbose_name="nombre")),
                (
                    "descripcion",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="descripción",
                    ),
                ),
                (
                    "duracion_dias",
                    models.IntegerField(
                        help_text="Período de facturación en días (30, 365, etc)",
                        verbose_name="duración (días)",
                    ),
                ),
                (
                    "precio_centavos",
                    models.IntegerField(
                        default=0,
                        help_text="Precio en centavos para evitar decimales",
                        verbose_name="precio (centavos)",
                    ),
                ),
                (
                    "moneda",
                    models.CharField(
                        default="USD",
                        help_text="Código de moneda ISO (USD, EUR, CLP)",
                        max_length=3,
                        verbose_name="moneda",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="activo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado en"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado en"),
                ),
            ],
            options={
                "verbose_name": "Plan",
                "verbose_name_plural": "Planes",
                "db_table": "planes",
                "ordering": ["precio_centavos"],
            },
        ),
        migrations.CreateModel(
            name="Suscripcion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("inicio", models.DateTimeField(verbose_name="inicio")),
                ("fin", models.DateTimeField(verbose_name="fin")),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("ACTIVA", "Activa"),
                            ("PAUSADA", "Pausada"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        db_index=True,
                        default="ACTIVA",
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                (
                    "referencia_pago",
                    models.CharField(
                        blank=True,
                        help_text="ID del pago en proveedor de pagos (Stripe, etc)",
                        max_length=255,
                        null=True,
                        verbose_name="referencia de pago",
                    ),
                ),
                (
                    "notas",
                    models.CharField(
                        blank=True,
                        help_text="Notas internas sobre la suscripción",
                        max_length=500,
                        null=True,
                        verbose_name="notas",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado en"),
                ),
                (
                    "empresa",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suscripcion",
                        to="app.empresa",
                        verbose_name="empresa",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="suscripciones",
                        to="app.plan",
                        verbose_name="plan",
                    ),
                ),
                (
                    "renovacion_de",
                    models.ForeignKey(
                        blank=True,
                        help_text="Si es renovación, referencia a la suscripción anterior",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="renovaciones",
                        to="app.suscripcion",
                        verbose_name="renovación de",
                    ),
                ),
            ],
            options={
                "verbose_name": "Suscripción",
                "verbose_name_plural": "Suscripciones",
                "db_table": "suscripciones",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Rol",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="nombre")),
                (
                    "descripcion",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="descripción",
                    ),
                ),
                (
                    "es_sistema",
                    models.BooleanField(
                        default=False,
                        help_text="Si es True, es un rol del sistema (no editable por usuarios)",
                        verbose_name="es sistema",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado en"),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="app.empresa",
                        verbose_name="empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rol",
                "verbose_name_plural": "Roles",
                "db_table": "roles",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Pago",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "empresa_slug",
                    models.CharField(
                        help_text="Slug de la empresa a crear",
                        max_length=255,
                        verbose_name="slug de empresa",
                    ),
                ),
                (
                    "empresa_nombre",
                    models.CharField(
                        help_text="Nombre de la empresa a crear",
                        max_length=255,
                        verbose_name="nombre de empresa",
                    ),
                ),
                (
                    "usuario_email",
                    models.CharField(
                        help_text="Email del usuario admin a crear",
                        max_length=255,
                        verbose_name="email del usuario",
                    ),
                ),
                (
                    "usuario_nombres",
                    models.CharField(
                        help_text="Nombres del usuario admin",
                        max_length=255,
                        verbose_name="nombres del usuario",
                    ),
                ),
                (
                    "usuario_apellidos",
                    models.CharField(
                        blank=True,
                        help_text="Apellidos del usuario admin",
                        max_length=255,
                        null=True,
                        verbose_name="apellidos del usuario",
                    ),
                ),
                (
                    "usuario_password",
                    models.CharField(
                        blank=True,
                        help_text="Password sin hashar (se hasheará al crear el usuario)",
                        max_length=255,
                        null=True,
                        verbose_name="password del usuario",
                    ),
                ),
                (
                    "amount_centavos",
                    models.IntegerField(
                        help_text="Monto en centavos", verbose_name="monto (centavos)"
                    ),
                ),
                (
                    "moneda",
                    models.CharField(
                        default="USD",
                        help_text="Código de moneda ISO (USD, EUR, CLP)",
                        max_length=3,
                        verbose_name="moneda",
                    ),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(
                        db_index=True,
                        help_text="ID del Payment Intent de Stripe",
                        max_length=255,
                        unique=True,
                        verbose_name="Stripe Payment Intent ID",
                    ),
                ),
                (
                    "stripe_session_id",
                    models.CharField(
                        blank=True,
                        help_text="ID de la Checkout Session (si usa Hosted Checkout)",
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="Stripe Session ID",
                    ),
                ),
                (
                    "stripe_customer_id",
                    models.CharField(
                        blank=True,
                        help_text="ID del customer en Stripe",
                        max_length=255,
                        null=True,
                        verbose_name="Stripe Customer ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("COMPLETADO", "Completado"),
                            ("FALLIDO", "Fallido"),
                            ("CANCELADO", "Cancelado"),
                            ("REEMBOLSO", "Reembolso"),
                        ],
                        db_index=True,
                        default="PENDIENTE",
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        default=dict,
                        help_text="Datos adicionales (ej: IP, user agent, etc)",
                        verbose_name="metadata",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="creado en"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado en"),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Cuándo se procesó el pago exitosamente",
                        null=True,
                        verbose_name="procesado en",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empresa creada tras pago exitoso",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pagos_iniciales",
                        to="app.empresa",
                        verbose_name="empresa",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pagos",
                        to="app.plan",
                        verbose_name="plan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pago",
                "verbose_name_plural": "Pagos",
                "db_table": "pagos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="empresa",
            index=models.Index(fields=["slug"], name="empresas_slug_1a17f5_idx"),
        ),
        migrations.AddIndex(
            model_name="empresa",
            index=models.Index(
                fields=["-created_at"], name="empresas_created_f19743_idx"
            ),
        ),
        migrations.AddField(
            model_name="auditoria",
            name="empresa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="eventos_auditoria",
                to="app.empresa",
                verbose_name="empresa",
            ),
        ),
        migrations.AddField(
            model_name="auditoria",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="eventos_generados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="usuario",
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="empresa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usuarios",
                to="app.empresa",
                verbose_name="empresa",
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="rol",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="usuarios",
                to="app.rol",
                verbose_name="rol",
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AddIndex(
            model_name="suscripcion",
            index=models.Index(
                fields=["empresa", "estado"], name="suscripcion_empresa_ef1cb9_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rol",
            unique_together={("empresa", "nombre")},
        ),
        migrations.AddIndex(
            model_name="pago",
            index=models.Index(
                fields=["stripe_payment_intent_id"], name="pagos_stripe__409b43_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pago",
            index=models.Index(
                fields=["empresa_slug"], name="pagos_empresa_c9f92d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pago",
            index=models.Index(
                fields=["usuario_email"], name="pagos_usuario_eed536_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pago",
            index=models.Index(fields=["-created_at"], name="pagos_created_0567cf_idx"),
        ),
        migrations.AddIndex(
            model_name="auditoria",
            index=models.Index(
                fields=["empresa", "-created_at"], name="auditoria_empresa_a1ce65_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditoria",
            index=models.Index(
                fields=["usuario", "accion"], name="auditoria_usuario_afae14_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usuario",
            index=models.Index(
                fields=["empresa", "email"], name="usuarios_empresa_a8ab90_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usuario",
            index=models.Index(fields=["email"], name="usuarios_email_0ff7b3_idx"),
        ),
        migrations.AddConstraint(
            model_name="usuario",
            constraint=models.UniqueConstraint(
                fields=("empresa", "email"), name="unique_empresa_email"
            ),
        ),
    ]
