# Generated by Django 4.2.8 on 2026-03-08 04:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="is_staff",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Designa si el usuario puede acceder al panel admin de Django",
                verbose_name="staff",
            ),
        ),
    ]
