# Generated by Django 4.2.8 on 2026-03-08 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_usuario_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="suscripcion",
            name="fecha_aplicacion_plan_pendiente",
            field=models.DateTimeField(
                blank=True,
                help_text="Fecha exacta en la que el plan pendiente pasa a ser el plan actual",
                null=True,
                verbose_name="fecha de aplicación del plan pendiente",
            ),
        ),
        migrations.AddField(
            model_name="suscripcion",
            name="plan_pendiente",
            field=models.ForeignKey(
                blank=True,
                help_text="Plan que se aplicará después de terminar el período actual",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="suscripciones_pendiente",
                to="app.plan",
                verbose_name="plan pendiente",
            ),
        ),
    ]
