# Generated by Django 4.2.8 on 2026-03-08 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_suscripcion_fecha_aplicacion_plan_pendiente_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="suscripcion",
            name="pago_plan_pendiente",
            field=models.OneToOneField(
                blank=True,
                help_text="Pago confirmado para el cambio pendiente (si existe)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="suscripcion_plan_pendiente",
                to="app.pago",
                verbose_name="pago del plan pendiente",
            ),
        ),
    ]
