# Generated by Django 4.2.8 on 2026-03-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_add_pago_plan_pendiente"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="stripe_customer_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="ID del customer en Stripe para facturación",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Stripe Customer ID",
            ),
        ),
    ]
