# Generated by Django 4.2.8 on 2026-03-12 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_empresa_stripe_customer_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="noti_email",
            field=models.BooleanField(
                default=True,
                help_text="Indica si el usuario desea recibir notificaciones por email",
                verbose_name="notificación por email",
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="noti_push",
            field=models.BooleanField(
                default=True,
                help_text="Indica si el usuario desea recibir notificaciones push",
                verbose_name="notificación push",
            ),
        ),
        migrations.AlterField(
            model_name="suscripcion",
            name="pago_plan_pendiente",
            field=models.OneToOneField(
                blank=True,
                help_text="Referencia AL REGISTRO ACTUAL del pago confirmado para el cambio pendiente. Este es un VINCULO al pago actualmente asociado con plan_pendiente. El historial completo de todos los pagos permanece en la tabla Pago (nunca se eliminan). Cuando se aplica el plan_pendiente automáticamente, este campo se limpia (SET_NULL). Un solo pago confirmado puede estar vinculado a la vez.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="suscripcion_plan_pendiente",
                to="app.pago",
                verbose_name="pago del plan pendiente",
            ),
        ),
    ]
