# Generated by Django 4.2.8 on 2026-03-17 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_cajausuario_categoriainventario_cita_compra_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="planserviciovehiculo",
            name="planes_serv_vehicul_c49af7_idx",
        ),
        migrations.AlterField(
            model_name="planserviciodetalle",
            name="origen",
            field=models.CharField(
                choices=[
                    ("CLIENTE", "Cliente"),
                    ("ASESOR", "Asesor"),
                    ("ADMIN", "Administrador"),
                    ("MECANICO", "Mecánico"),
                ],
                help_text="Quién agregó este servicio",
                max_length=20,
                verbose_name="origen",
            ),
        ),
        migrations.AlterField(
            model_name="planserviciovehiculo",
            name="estado",
            field=models.CharField(
                choices=[("LIBRE", "Libre"), ("EN_EJECUCION", "En ejecución")],
                db_index=True,
                default="LIBRE",
                max_length=30,
                verbose_name="estado",
            ),
        ),
        migrations.AlterField(
            model_name="planserviciovehiculo",
            name="vehiculo",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plan_servicio",
                to="app.vehiculo",
                verbose_name="vehículo",
            ),
        ),
    ]
