# Generated by Django 4.2.8 on 2026-03-22 22:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0010_remove_versionado_planes_endurecer_nulabilidades"),
    ]

    operations = [
        migrations.CreateModel(
            name="CitaDetalle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("PROGRAMADO", "Programado"),
                            ("EN_PROCESO", "En proceso"),
                            ("FINALIZADO", "Finalizado"),
                            ("INNECESARIO", "Innecesario"),
                            ("DIFERIDO", "Diferido"),
                            ("RECOMENDADO", "Recomendado"),
                        ],
                        db_index=True,
                        default="PROGRAMADO",
                        help_text="Estado del detalle dentro de la cita",
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                (
                    "tiempo_estandar_min",
                    models.IntegerField(
                        help_text="Copia snapshot del tiempo estándar al momento de la cita",
                        verbose_name="tiempo estándar (minutos)",
                    ),
                ),
                (
                    "precio_referencial",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Copia snapshot del precio al momento de la cita",
                        max_digits=12,
                        verbose_name="precio referencial",
                    ),
                ),
                (
                    "observaciones",
                    models.CharField(
                        blank=True,
                        help_text="Observaciones específicas para este detalle en esta cita",
                        max_length=500,
                        null=True,
                        verbose_name="observaciones",
                    ),
                ),
                (
                    "orden_visual",
                    models.IntegerField(
                        default=0,
                        help_text="Orden en que se muestra en la lista de la cita",
                        verbose_name="orden visual",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado en"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado en"),
                ),
                (
                    "cita",
                    models.ForeignKey(
                        help_text="Referencia a la cita que contiene este detalle",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="app.cita",
                        verbose_name="cita",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="citas_detalles",
                        to="app.empresa",
                        verbose_name="empresa",
                    ),
                ),
                (
                    "plan_detalle",
                    models.ForeignKey(
                        blank=True,
                        help_text="Referencia al detalle original del plan del vehículo",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="citas_detalles",
                        to="app.planserviciodetalle",
                        verbose_name="detalle del plan",
                    ),
                ),
                (
                    "servicio_catalogo",
                    models.ForeignKey(
                        blank=True,
                        help_text="Copia del servicio al momento de la cita (para historicidad)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="citas_detalles",
                        to="app.serviciocatalogo",
                        verbose_name="servicio catálogo (snapshot)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Cita",
                "verbose_name_plural": "Detalles de Cita",
                "db_table": "citas_detalles",
                "ordering": ["cita", "orden_visual", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["cita", "estado"], name="citas_detal_cita_id_95c4c9_idx"
                    ),
                    models.Index(
                        fields=["plan_detalle", "estado"],
                        name="citas_detal_plan_de_aafead_idx",
                    ),
                    models.Index(
                        fields=["empresa", "estado"],
                        name="citas_detal_empresa_90f191_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="citadetalle",
            constraint=models.UniqueConstraint(
                fields=("cita", "plan_detalle"), name="unique_cita_plan_detalle"
            ),
        ),
    ]
