# Generated by Django 4.2.8 on 2026-03-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0011_citadetalle_citadetalle_unique_cita_plan_detalle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cita",
            name="estado",
            field=models.CharField(
                choices=[
                    ("PENDIENTE_APROBACION", "Pendiente de aprobación"),
                    ("PROGRAMADA", "Programada"),
                    ("EN_ESPERA_INGRESO", "En espera de ingreso"),
                    ("EN_PROCESO", "En proceso"),
                    ("CANCELADA", "Cancelada"),
                    ("NO_SHOW", "No asistió"),
                    ("FINALIZADA", "Finalizada"),
                    ("REPROGRAMADA", "Reprogramada"),
                ],
                db_index=True,
                default="PROGRAMADA",
                max_length=30,
                verbose_name="estado",
            ),
        ),
    ]
