# Generated by Django 4.2.8 on 2026-04-23 01:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0013_remove_recepciones_add_cita_vehiculo_devuelto"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecepcionVehiculo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "fecha_recepcion",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Fecha/hora cuando se registra la recepción",
                        verbose_name="fecha de recepción",
                    ),
                ),
                (
                    "kilometraje_ingreso",
                    models.IntegerField(
                        help_text="Kilómetros del vehículo al ingresar",
                        verbose_name="kilometraje de ingreso",
                    ),
                ),
                (
                    "nivel_combustible",
                    models.CharField(
                        choices=[
                            ("1/4", "1/4 de tanque"),
                            ("1/2", "1/2 de tanque"),
                            ("3/4", "3/4 de tanque"),
                            ("LLENO", "Lleno"),
                        ],
                        default="1/2",
                        max_length=20,
                        verbose_name="nivel de combustible",
                    ),
                ),
                (
                    "condicion_general",
                    models.CharField(
                        help_text="Observaciones sobre el estado general del vehículo",
                        max_length=500,
                        verbose_name="condición general",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True,
                        help_text="Notas adicionales sobre la recepción",
                        null=True,
                        verbose_name="observaciones adicionales",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado en"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado en"),
                ),
                (
                    "asesor_registra",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recepciones_registradas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="asesor que registra",
                    ),
                ),
                (
                    "cita",
                    models.OneToOneField(
                        help_text="Una recepción por cita",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recepcion",
                        to="app.cita",
                        verbose_name="cita",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recepciones_vehiculo",
                        to="app.empresa",
                        verbose_name="empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recepción Vehículo",
                "verbose_name_plural": "Recepciones Vehículos",
                "db_table": "recepciones_vehiculo",
                "ordering": ["-fecha_recepcion"],
                "indexes": [
                    models.Index(
                        fields=["empresa", "cita"],
                        name="recepciones_empresa_97380b_idx",
                    ),
                    models.Index(
                        fields=["asesor_registra", "-fecha_recepcion"],
                        name="recepciones_asesor__eb19cf_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="recepcionvehiculo",
            constraint=models.UniqueConstraint(
                fields=("empresa", "cita"), name="uq_recepcion_empresa_cita"
            ),
        ),
    ]
