# Generated by Django 4.2.8 on 2026-05-07 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administracion_acceso_configuracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversacionIA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(default='ACTIVA', help_text='ACTIVA, ARCHIVADA, CERRADA', max_length=50, verbose_name='estado')),
                ('canal', models.CharField(choices=[('WEB', 'Web'), ('MOVIL', 'Móvil')], max_length=20, verbose_name='canal')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones_ia', to='administracion_acceso_configuracion.empresa', verbose_name='empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones_ia', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'Conversación IA',
                'verbose_name_plural': 'Conversaciones IA',
                'db_table': 'conversaciones_ia',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(help_text='Tipo de notificación (ej: cita_programada, pago_recibido)', max_length=100, verbose_name='tipo')),
                ('titulo', models.CharField(max_length=255, verbose_name='título')),
                ('mensaje', models.CharField(max_length=500, verbose_name='mensaje')),
                ('entidad_tipo', models.CharField(blank=True, help_text='Tipo de entidad relacionada (Cita, Pago, etc)', max_length=100, null=True, verbose_name='tipo de entidad')),
                ('entidad_id', models.UUIDField(blank=True, help_text='ID de la entidad relacionada', null=True, verbose_name='ID de entidad')),
                ('leida_at', models.DateTimeField(blank=True, null=True, verbose_name='leída en')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='administracion_acceso_configuracion.empresa', verbose_name='empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_recibidas', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notificaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgramacionBackupEmpresa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=False, verbose_name='activo')),
                ('frecuencia', models.CharField(choices=[('DIARIO', 'Diario'), ('CADA_N_DIAS', 'Cada N días')], default='DIARIO', max_length=20, verbose_name='frecuencia')),
                ('intervalo_dias', models.IntegerField(default=1, verbose_name='intervalo días')),
                ('hora_ejecucion', models.TimeField(default=django.utils.timezone.now, verbose_name='hora de ejecución')),
                ('tolera_compensacion', models.BooleanField(default=True, verbose_name='tolerar compensación')),
                ('ultima_ejecucion_at', models.DateTimeField(blank=True, null=True, verbose_name='última ejecución')),
                ('proxima_ejecucion_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='próxima ejecución')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='programacion_backup', to='administracion_acceso_configuracion.empresa', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'Programación Backup Empresa',
                'verbose_name_plural': 'Programación Backups Empresa',
                'db_table': 'programacion_backups_empresa',
            },
        ),
        migrations.CreateModel(
            name='MensajeIA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rol_mensaje', models.CharField(choices=[('USUARIO', 'Usuario'), ('ASISTENTE', 'Asistente'), ('SISTEMA', 'Sistema')], help_text='USUARIO, ASISTENTE, SISTEMA', max_length=20, verbose_name='rol del mensaje')),
                ('contenido', models.TextField(verbose_name='contenido')),
                ('metadata', models.JSONField(default=dict, help_text='Datos adicionales (tokens, modelo, etc)', verbose_name='metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='comunicacion_control_inteligencia.conversacionia', verbose_name='conversación')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_ia', to='administracion_acceso_configuracion.empresa', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'Mensaje IA',
                'verbose_name_plural': 'Mensajes IA',
                'db_table': 'mensajes_ia',
                'ordering': ['conversacion', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='BackupEmpresa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('EN_PROCESO', 'En proceso'), ('COMPLETADO', 'Completado'), ('FALLIDO', 'Fallido')], db_index=True, default='EN_PROCESO', max_length=20, verbose_name='estado')),
                ('tipo', models.CharField(choices=[('MANUAL', 'Manual'), ('AUTOMATICO', 'Automático'), ('COMPENSACION', 'Compensación')], default='MANUAL', max_length=20, verbose_name='tipo')),
                ('alcance', models.CharField(choices=[('TENANT_COMPLETO', 'Tenant completo')], default='TENANT_COMPLETO', max_length=30, verbose_name='alcance')),
                ('iniciado_at', models.DateTimeField(auto_now_add=True, verbose_name='iniciado en')),
                ('completado_at', models.DateTimeField(blank=True, null=True, verbose_name='completado en')),
                ('archivo_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='ruta archivo')),
                ('tamano_bytes', models.BigIntegerField(default=0, verbose_name='tamaño (bytes)')),
                ('error', models.CharField(blank=True, max_length=1000, null=True, verbose_name='error')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='administracion_acceso_configuracion.empresa', verbose_name='empresa')),
                ('solicitado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backups_solicitados', to=settings.AUTH_USER_MODEL, verbose_name='solicitado por')),
            ],
            options={
                'verbose_name': 'Backup Empresa',
                'verbose_name_plural': 'Backups Empresa',
                'db_table': 'backups_empresa',
                'ordering': ['-iniciado_at'],
            },
        ),
        migrations.CreateModel(
            name='AccionIA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accion', models.CharField(help_text='Código de la acción (ej: crear_cita, registrar_pago)', max_length=100, verbose_name='acción')),
                ('parametros', models.JSONField(default=dict, help_text='Parámetros de la acción', verbose_name='parámetros')),
                ('estado', models.CharField(default='PENDIENTE', help_text='PENDIENTE, CONFIRMADA, EJECUTADA, CANCELADA', max_length=50, verbose_name='estado')),
                ('requiere_confirmacion', models.BooleanField(default=False, verbose_name='requiere confirmación')),
                ('confirmada_at', models.DateTimeField(blank=True, null=True, verbose_name='confirmada en')),
                ('ejecutada_at', models.DateTimeField(blank=True, null=True, verbose_name='ejecutada en')),
                ('resultado', models.JSONField(default=dict, help_text='Resultado de la ejecución', verbose_name='resultado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones', to='comunicacion_control_inteligencia.conversacionia', verbose_name='conversación')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones_ia', to='administracion_acceso_configuracion.empresa', verbose_name='empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones_ia', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'Acción IA',
                'verbose_name_plural': 'Acciones IA',
                'db_table': 'acciones_ia',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReporteGenerado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_reporte', models.CharField(choices=[('VEHICULO', 'Vehículo'), ('PRESUPUESTO', 'Presupuesto'), ('INVENTARIO', 'Inventario'), ('GLOBAL', 'Global')], max_length=20, verbose_name='tipo de reporte')),
                ('formato', models.CharField(choices=[('PDF', 'PDF'), ('CSV', 'CSV'), ('HTML', 'HTML')], max_length=20, verbose_name='formato')),
                ('filtros', models.JSONField(default=dict, help_text='Filtros usados para generar el reporte', verbose_name='filtros')),
                ('archivo_url', models.CharField(blank=True, help_text='URL del archivo generado', max_length=500, null=True, verbose_name='URL del archivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_generados', to='administracion_acceso_configuracion.empresa', verbose_name='empresa')),
                ('generado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_generados', to=settings.AUTH_USER_MODEL, verbose_name='generado por')),
            ],
            options={
                'verbose_name': 'Reporte Generado',
                'verbose_name_plural': 'Reportes Generados',
                'db_table': 'reportes_generados',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['generado_por', '-created_at'], name='reportes_ge_generad_89f5aa_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificacionEntrega',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canal', models.CharField(choices=[('WEB', 'Web'), ('EMAIL', 'Email')], max_length=20, verbose_name='canal')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADO', 'Enviado'), ('FALLIDO', 'Fallido')], db_index=True, default='PENDIENTE', max_length=20, verbose_name='estado')),
                ('destinatario', models.CharField(help_text='Email, token push, etc', max_length=255, verbose_name='destinatario')),
                ('enviado_at', models.DateTimeField(blank=True, null=True, verbose_name='enviado en')),
                ('error_mensaje', models.CharField(blank=True, max_length=500, null=True, verbose_name='mensaje de error')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_entrega', to='administracion_acceso_configuracion.empresa', verbose_name='empresa')),
                ('notificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='comunicacion_control_inteligencia.notificacion', verbose_name='notificación')),
            ],
            options={
                'verbose_name': 'Entrega Notificación',
                'verbose_name_plural': 'Entregas Notificaciones',
                'db_table': 'notificaciones_entrega',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['notificacion', 'canal'], name='notificacio_notific_bdc75a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['usuario', '-created_at'], name='notificacio_usuario_ff0f5f_idx'),
        ),
        migrations.AddIndex(
            model_name='mensajeia',
            index=models.Index(fields=['conversacion', '-created_at'], name='mensajes_ia_convers_1ebdd6_idx'),
        ),
        migrations.AddIndex(
            model_name='conversacionia',
            index=models.Index(fields=['usuario', '-updated_at'], name='conversacio_usuario_4b3fb4_idx'),
        ),
        migrations.AddIndex(
            model_name='backupempresa',
            index=models.Index(fields=['empresa', '-iniciado_at'], name='backups_emp_empresa_1ba860_idx'),
        ),
        migrations.AddIndex(
            model_name='accionia',
            index=models.Index(fields=['conversacion', 'estado'], name='acciones_ia_convers_6b1adb_idx'),
        ),
    ]
