# Generated by Django 4.2.8 on 2026-05-07 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administracion_acceso_configuracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('PENDIENTE_APROBACION', 'Pendiente de aprobación'), ('PROGRAMADA', 'Programada'), ('EN_ESPERA_INGRESO', 'En espera de ingreso'), ('EN_PROCESO', 'En proceso'), ('CANCELADA', 'Cancelada'), ('NO_SHOW', 'No asistió'), ('FINALIZADA', 'Finalizada'), ('REPROGRAMADA', 'Reprogramada')], db_index=True, default='PROGRAMADA', max_length=30, verbose_name='estado')),
                ('canal_origen', models.CharField(choices=[('CLIENTE', 'Cliente'), ('ASESOR', 'Asesor')], help_text='Quién agendó la cita', max_length=20, verbose_name='canal de origen')),
                ('fecha_hora_inicio_programada', models.DateTimeField(verbose_name='inicio programado')),
                ('fecha_hora_fin_programada', models.DateTimeField(verbose_name='fin programado')),
                ('duracion_estimada_min', models.IntegerField(help_text='Duración estimada de la cita', verbose_name='duración estimada (minutos)')),
                ('llegada_real_at', models.DateTimeField(blank=True, help_text='Cuándo llegó el vehículo efectivamente', null=True, verbose_name='llegada real')),
                ('reprogramaciones_count', models.IntegerField(default=0, help_text='Número de veces que se reprogramó', verbose_name='cantidad de reprogramaciones')),
                ('ultima_reprogramacion_at', models.DateTimeField(blank=True, null=True, verbose_name='última reprogramación')),
                ('motivo_ultima_reprogramacion', models.CharField(blank=True, max_length=500, null=True, verbose_name='motivo de última reprogramación')),
                ('motivo_visita', models.CharField(blank=True, help_text='Resumen de por qué el cliente trae el vehículo', max_length=500, null=True, verbose_name='motivo de la visita')),
                ('observaciones_cliente', models.CharField(blank=True, max_length=500, null=True, verbose_name='observaciones del cliente')),
                ('motivo_cancelacion', models.CharField(blank=True, max_length=500, null=True, verbose_name='motivo de cancelación')),
                ('no_show_marcado_at', models.DateTimeField(blank=True, null=True, verbose_name='marcado como no-show en')),
                ('finalizada_at', models.DateTimeField(blank=True, null=True, verbose_name='finalizada en')),
                ('vehiculo_devuelto_at', models.DateTimeField(blank=True, help_text='Cuándo se marcó el vehículo como recolectado/devuelto al cliente', null=True, verbose_name='vehículo devuelto en')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('asesor_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_asesor', to=settings.AUTH_USER_MODEL, verbose_name='asesor responsable')),
                ('cancelada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_canceladas', to=settings.AUTH_USER_MODEL, verbose_name='cancelada por')),
                ('cliente', models.ForeignKey(blank=True, help_text='Usuario cliente/propietario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_cliente', to=settings.AUTH_USER_MODEL, verbose_name='cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='administracion_acceso_configuracion.empresa', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'db_table': 'citas',
                'ordering': ['-fecha_hora_inicio_programada'],
            },
        ),
        migrations.CreateModel(
            name='EspacioTrabajo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(db_index=True, help_text='Código único del espacio (ej: TALLER_1)', max_length=50, verbose_name='código')),
                ('nombre', models.CharField(max_length=255, verbose_name='nombre')),
                ('tipo', models.CharField(choices=[('TALLER', 'Taller'), ('CHEQUEO', 'Chequeo'), ('GARAJE', 'Garaje'), ('LAVADO', 'Lavado')], max_length=20, verbose_name='tipo')),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCUPADO', 'Ocupado'), ('MANTENIMIENTO', 'Mantenimiento'), ('TIEMPO_EXTENDIDO', 'Tiempo extendido')], db_index=True, default='DISPONIBLE', max_length=20, verbose_name='estado')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('observaciones', models.CharField(blank=True, max_length=500, null=True, verbose_name='observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='espacios_trabajo', to='administracion_acceso_configuracion.empresa', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'Espacio de Trabajo',
                'verbose_name_plural': 'Espacios de Trabajo',
                'db_table': 'espacios_trabajo',
                'ordering': ['tipo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('placa', models.CharField(db_index=True, help_text='Placa del vehículo (única por empresa)', max_length=50, verbose_name='placa')),
                ('marca', models.CharField(max_length=100, verbose_name='marca')),
                ('modelo', models.CharField(max_length=100, verbose_name='modelo')),
                ('anio', models.IntegerField(help_text='Año de fabricación', verbose_name='año')),
                ('color', models.CharField(blank=True, max_length=100, null=True, verbose_name='color')),
                ('kilometraje_actual', models.IntegerField(default=0, help_text='Último kilometraje registrado', verbose_name='kilometraje actual')),
                ('vin_chasis', models.CharField(blank=True, help_text='Número de identificación del vehículo', max_length=100, null=True, verbose_name='VIN/Chasis')),
                ('motor', models.CharField(blank=True, help_text='Tipo de motor', max_length=100, null=True, verbose_name='motor')),
                ('observaciones', models.CharField(blank=True, help_text='Observaciones generales del vehículo', max_length=500, null=True, verbose_name='observaciones')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], db_index=True, default='ACTIVO', max_length=20, verbose_name='estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='administracion_acceso_configuracion.empresa', verbose_name='empresa')),
                ('propietario', models.ForeignKey(help_text='Usuario propietario del vehículo', on_delete=django.db.models.deletion.RESTRICT, related_name='vehiculos', to=settings.AUTH_USER_MODEL, verbose_name='propietario')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'db_table': 'vehiculos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServicioCatalogo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(db_index=True, help_text='Código único del servicio (ej: CAMBIO_ACEITE)', max_length=50, verbose_name='código')),
                ('nombre', models.CharField(max_length=255, verbose_name='nombre')),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True, verbose_name='descripción')),
                ('tiempo_estandar_min', models.IntegerField(help_text='Tiempo estándar de ejecución', verbose_name='tiempo estándar (minutos)')),
                ('precio_base', models.DecimalField(decimal_places=2, help_text='Precio base del servicio', max_digits=12, verbose_name='precio base')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_catalogo', to='administracion_acceso_configuracion.empresa', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'Servicio Catálogo',
                'verbose_name_plural': 'Servicios Catálogo',
                'db_table': 'servicios_catalogo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PlanServicioVehiculo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('LIBRE', 'Libre'), ('EN_EJECUCION', 'En ejecución')], db_index=True, default='LIBRE', max_length=30, verbose_name='estado')),
                ('descripcion_general', models.CharField(blank=True, help_text='Descripción general del plan', max_length=500, null=True, verbose_name='descripción general')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes_creados', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_servicio_vehiculo', to='administracion_acceso_configuracion.empresa', verbose_name='empresa')),
                ('vehiculo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan_servicio', to='vehiculos_servicios_plan_citas.vehiculo', verbose_name='vehículo')),
            ],
            options={
                'verbose_name': 'Plan de Servicio del Vehículo',
                'verbose_name_plural': 'Planes de Servicio del Vehículo',
                'db_table': 'planes_servicio_vehiculo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanServicioDetalle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROGRAMADO', 'Programado'), ('EN_PROCESO', 'En proceso'), ('FINALIZADO', 'Finalizado'), ('INNECESARIO', 'Innecesario'), ('DIFERIDO', 'Diferido'), ('RECOMENDADO', 'Recomendado')], db_index=True, default='PENDIENTE', max_length=20, verbose_name='estado')),
                ('origen', models.CharField(choices=[('CLIENTE', 'Cliente'), ('ASESOR', 'Asesor'), ('ADMIN', 'Administrador'), ('MECANICO', 'Mecánico')], help_text='Quién agregó este servicio', max_length=20, verbose_name='origen')),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=20, verbose_name='prioridad')),
                ('tiempo_estandar_min', models.IntegerField(help_text='Tiempo estándar para este servicio', verbose_name='tiempo estándar (minutos)')),
                ('precio_referencial', models.DecimalField(decimal_places=2, default=0, help_text='Precio estimado', max_digits=12, verbose_name='precio referencial')),
                ('observaciones', models.CharField(blank=True, max_length=500, null=True, verbose_name='observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_servicio_detalle', to='administracion_acceso_configuracion.empresa', verbose_name='empresa')),
                ('plan_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='vehiculos_servicios_plan_citas.planserviciovehiculo', verbose_name='plan de servicio')),
                ('recomendado_por', models.ForeignKey(blank=True, help_text='Si origen es MECANICO, usuario que recomendó', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_recomendados', to=settings.AUTH_USER_MODEL, verbose_name='recomendado por')),
                ('servicio_catalogo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='planes_detalles', to='vehiculos_servicios_plan_citas.serviciocatalogo', verbose_name='servicio catálogo')),
            ],
            options={
                'verbose_name': 'Detalle Plan de Servicio',
                'verbose_name_plural': 'Detalles Plan de Servicio',
                'db_table': 'planes_servicio_detalle',
                'ordering': ['plan_servicio', 'prioridad', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HorarioEspacioTrabajo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], help_text='0=Lunes, 6=Domingo', verbose_name='día de la semana')),
                ('hora_inicio', models.TimeField(verbose_name='hora inicio')),
                ('hora_fin', models.TimeField(verbose_name='hora fin')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_espacios', to='administracion_acceso_configuracion.empresa', verbose_name='empresa')),
                ('espacio_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='vehiculos_servicios_plan_citas.espaciotrabajo', verbose_name='espacio de trabajo')),
            ],
            options={
                'verbose_name': 'Horario Espacio de Trabajo',
                'verbose_name_plural': 'Horarios Espacios de Trabajo',
                'db_table': 'horarios_espacios_trabajo',
                'ordering': ['espacio_trabajo', 'dia_semana'],
            },
        ),
        migrations.CreateModel(
            name='CitaEspacioSegmento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('orden_segmento', models.IntegerField(help_text='Orden en que ocurren los segmentos en la cita (1, 2, 3...)', verbose_name='orden del segmento')),
                ('tipo_segmento', models.CharField(choices=[('CHEQUEO', 'Chequeo'), ('TALLER', 'Taller'), ('LAVADO', 'Lavado'), ('GARAJE_ESPERA', 'Garaje de espera'), ('GARAJE_ENTREGA', 'Garaje de entrega')], max_length=20, verbose_name='tipo de segmento')),
                ('estado_segmento', models.CharField(choices=[('RESERVADO', 'Reservado'), ('OCUPADO', 'Ocupado'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado'), ('EXTENDIDO', 'Extendido')], db_index=True, default='RESERVADO', max_length=20, verbose_name='estado del segmento')),
                ('inicio_programado', models.DateTimeField(verbose_name='inicio programado')),
                ('fin_programado', models.DateTimeField(verbose_name='fin programado')),
                ('inicio_real', models.DateTimeField(blank=True, null=True, verbose_name='inicio real')),
                ('fin_real', models.DateTimeField(blank=True, null=True, verbose_name='fin real')),
                ('motivo', models.CharField(blank=True, help_text='Motivo de cambios o observaciones', max_length=500, null=True, verbose_name='motivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='espacios_segmentos', to='vehiculos_servicios_plan_citas.cita', verbose_name='cita')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_espacios_segmentos', to='administracion_acceso_configuracion.empresa', verbose_name='empresa')),
                ('espacio_trabajo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_segmentos', to='vehiculos_servicios_plan_citas.espaciotrabajo', verbose_name='espacio de trabajo')),
            ],
            options={
                'verbose_name': 'Segmento Cita-Espacio',
                'verbose_name_plural': 'Segmentos Cita-Espacio',
                'db_table': 'citas_espacios_segmentos',
                'ordering': ['cita', 'orden_segmento'],
            },
        ),
        migrations.CreateModel(
            name='CitaDetalle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROGRAMADO', 'Programado'), ('EN_PROCESO', 'En proceso'), ('FINALIZADO', 'Finalizado'), ('INNECESARIO', 'Innecesario'), ('DIFERIDO', 'Diferido'), ('RECOMENDADO', 'Recomendado')], db_index=True, default='PROGRAMADO', help_text='Estado del detalle dentro de la cita', max_length=20, verbose_name='estado')),
                ('tiempo_estandar_min', models.IntegerField(help_text='Copia snapshot del tiempo estándar al momento de la cita', verbose_name='tiempo estándar (minutos)')),
                ('precio_referencial', models.DecimalField(decimal_places=2, default=0, help_text='Copia snapshot del precio al momento de la cita', max_digits=12, verbose_name='precio referencial')),
                ('observaciones', models.CharField(blank=True, help_text='Observaciones específicas para este detalle en esta cita', max_length=500, null=True, verbose_name='observaciones')),
                ('orden_visual', models.IntegerField(default=0, help_text='Orden en que se muestra en la lista de la cita', verbose_name='orden visual')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('cita', models.ForeignKey(help_text='Referencia a la cita que contiene este detalle', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='vehiculos_servicios_plan_citas.cita', verbose_name='cita')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_detalles', to='administracion_acceso_configuracion.empresa', verbose_name='empresa')),
                ('plan_detalle', models.ForeignKey(blank=True, help_text='Referencia al detalle original del plan del vehículo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_detalles', to='vehiculos_servicios_plan_citas.planserviciodetalle', verbose_name='detalle del plan')),
                ('servicio_catalogo', models.ForeignKey(blank=True, help_text='Copia del servicio al momento de la cita (para historicidad)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_detalles', to='vehiculos_servicios_plan_citas.serviciocatalogo', verbose_name='servicio catálogo (snapshot)')),
            ],
            options={
                'verbose_name': 'Detalle de Cita',
                'verbose_name_plural': 'Detalles de Cita',
                'db_table': 'citas_detalles',
                'ordering': ['cita', 'orden_visual', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='cita',
            name='plan_servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='vehiculos_servicios_plan_citas.planserviciovehiculo', verbose_name='plan de servicio'),
        ),
        migrations.AddField(
            model_name='cita',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='vehiculos_servicios_plan_citas.vehiculo', verbose_name='vehículo'),
        ),
        migrations.AddIndex(
            model_name='vehiculo',
            index=models.Index(fields=['empresa', 'placa'], name='vehiculos_empresa_5e1a80_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiculo',
            index=models.Index(fields=['propietario'], name='vehiculos_propiet_391368_idx'),
        ),
        migrations.AddConstraint(
            model_name='vehiculo',
            constraint=models.UniqueConstraint(fields=('empresa', 'placa'), name='unique_empresa_placa'),
        ),
        migrations.AddIndex(
            model_name='serviciocatalogo',
            index=models.Index(fields=['empresa', 'activo'], name='servicios_c_empresa_159ff3_idx'),
        ),
        migrations.AddConstraint(
            model_name='serviciocatalogo',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='unique_empresa_codigo_servicio'),
        ),
        migrations.AddIndex(
            model_name='planserviciodetalle',
            index=models.Index(fields=['plan_servicio', 'estado'], name='planes_serv_plan_se_81f284_idx'),
        ),
        migrations.AddIndex(
            model_name='horarioespaciotrabajo',
            index=models.Index(fields=['espacio_trabajo', 'dia_semana'], name='horarios_es_espacio_a1a4c8_idx'),
        ),
        migrations.AddIndex(
            model_name='espaciotrabajo',
            index=models.Index(fields=['empresa', 'tipo', 'estado'], name='espacios_tr_empresa_adc91e_idx'),
        ),
        migrations.AddConstraint(
            model_name='espaciotrabajo',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='unique_empresa_codigo_espacio'),
        ),
        migrations.AddIndex(
            model_name='citaespaciosegmento',
            index=models.Index(fields=['cita', 'orden_segmento'], name='citas_espac_cita_id_c0d27d_idx'),
        ),
        migrations.AddIndex(
            model_name='citadetalle',
            index=models.Index(fields=['cita', 'estado'], name='citas_detal_cita_id_95c4c9_idx'),
        ),
        migrations.AddIndex(
            model_name='citadetalle',
            index=models.Index(fields=['plan_detalle', 'estado'], name='citas_detal_plan_de_aafead_idx'),
        ),
        migrations.AddIndex(
            model_name='citadetalle',
            index=models.Index(fields=['empresa', 'estado'], name='citas_detal_empresa_90f191_idx'),
        ),
        migrations.AddConstraint(
            model_name='citadetalle',
            constraint=models.UniqueConstraint(fields=('cita', 'plan_detalle'), name='unique_cita_plan_detalle'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['empresa', 'estado', '-fecha_hora_inicio_programada'], name='citas_empresa_4c8122_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['vehiculo'], name='citas_vehicul_65921b_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['cliente'], name='citas_cliente_656732_idx'),
        ),
    ]
