# Generated by Django 4.2.8 on 2026-05-07 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehiculos_servicios_plan_citas', '0001_initial'),
        ('administracion_acceso_configuracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenTrabajoGlobal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(db_index=True, help_text='Número único de la orden', max_length=100, verbose_name='número')),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('ASIGNADA', 'Asignada'), ('EN_PROCESO', 'En proceso'), ('PAUSADA', 'Pausada'), ('FINALIZADA', 'Finalizada'), ('CERRADA', 'Cerrada'), ('CANCELADA', 'Cancelada')], db_index=True, default='ABIERTA', max_length=20, verbose_name='estado')),
                ('observaciones', models.CharField(blank=True, max_length=500, null=True, verbose_name='observaciones')),
                ('fecha_apertura', models.DateTimeField(verbose_name='fecha de apertura')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True, verbose_name='fecha de cierre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('asesor_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='asesor responsable')),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orden_trabajo', to='vehiculos_servicios_plan_citas.cita', verbose_name='cita')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_trabajo_global', to='administracion_acceso_configuracion.empresa', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'Orden de Trabajo Global',
                'verbose_name_plural': 'Órdenes de Trabajo Global',
                'db_table': 'ordenes_trabajo_global',
                'ordering': ['-fecha_apertura'],
            },
        ),
        migrations.CreateModel(
            name='PresupuestoCita',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('COMUNICADO', 'Comunicado'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('AJUSTADO', 'Ajustado'), ('CERRADO', 'Cerrado')], db_index=True, default='BORRADOR', max_length=20, verbose_name='estado')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='subtotal')),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='descuento')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='total')),
                ('comunicado_at', models.DateTimeField(blank=True, null=True, verbose_name='comunicado en')),
                ('observaciones', models.CharField(blank=True, max_length=500, null=True, verbose_name='observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presupuesto', to='vehiculos_servicios_plan_citas.cita', verbose_name='cita')),
                ('comunicado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presupuestos_comunicados', to=settings.AUTH_USER_MODEL, verbose_name='comunicado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos_cita', to='administracion_acceso_configuracion.empresa', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'Presupuesto Cita',
                'verbose_name_plural': 'Presupuestos Cita',
                'db_table': 'presupuestos_cita',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PresupuestoDetalle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(help_text='Descripción del ítem (puede ser manual)', max_length=255, verbose_name='descripción')),
                ('cantidad', models.IntegerField(default=1, verbose_name='cantidad')),
                ('tiempo_estandar_min', models.IntegerField(default=0, verbose_name='tiempo estándar (minutos)')),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='precio unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='subtotal')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('EXCLUIDO', 'Excluido')], default='ACTIVO', max_length=20, verbose_name='estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos_detalle', to='administracion_acceso_configuracion.empresa', verbose_name='empresa')),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='atencion_tecnica_ejecucion.presupuestocita', verbose_name='presupuesto')),
                ('servicio_catalogo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presupuestos_detalles', to='vehiculos_servicios_plan_citas.serviciocatalogo', verbose_name='servicio catálogo')),
            ],
            options={
                'verbose_name': 'Detalle Presupuesto',
                'verbose_name_plural': 'Detalles Presupuesto',
                'db_table': 'presupuestos_detalle',
                'ordering': ['presupuesto', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrdenTrabajoGlobalMecanico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('es_principal', models.BooleanField(default=False, help_text='Si hay un mecánico principal', verbose_name='es principal')),
                ('asignado_at', models.DateTimeField(verbose_name='asignado en')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_mecanicos', to='administracion_acceso_configuracion.empresa', verbose_name='empresa')),
                ('mecanico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_trabajo', to=settings.AUTH_USER_MODEL, verbose_name='mecánico')),
                ('orden_global', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mecanicos_asignados', to='atencion_tecnica_ejecucion.ordentrabajoglobal', verbose_name='orden de trabajo')),
            ],
            options={
                'verbose_name': 'Mecánico Orden Trabajo',
                'verbose_name_plural': 'Mecánicos Órdenes Trabajo',
                'db_table': 'ordenes_trabajo_global_mecanicos',
                'ordering': ['-asignado_at'],
            },
        ),
        migrations.CreateModel(
            name='OrdenTrabajoDetalle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('POR_HACER', 'Por hacer'), ('EN_PROCESO', 'En proceso'), ('FINALIZADO', 'Finalizado'), ('INNECESARIO', 'Innecesario'), ('PAUSADO', 'Pausado')], db_index=True, default='POR_HACER', max_length=20, verbose_name='estado')),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=20, verbose_name='prioridad')),
                ('tiempo_estandar_min', models.IntegerField(verbose_name='tiempo estándar (minutos)')),
                ('tiempo_real_min', models.IntegerField(blank=True, null=True, verbose_name='tiempo real (minutos)')),
                ('visible_cliente', models.BooleanField(default=True, help_text='Si el cliente puede verlo en su app', verbose_name='visible para cliente')),
                ('observaciones_asesor', models.CharField(blank=True, max_length=500, null=True, verbose_name='observaciones del asesor')),
                ('observaciones_mecanico', models.CharField(blank=True, max_length=500, null=True, verbose_name='observaciones del mecánico')),
                ('inicio_real', models.DateTimeField(blank=True, null=True, verbose_name='inicio real')),
                ('fin_real', models.DateTimeField(blank=True, null=True, verbose_name='fin real')),
                ('precio_base', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='precio base')),
                ('orden_visual', models.IntegerField(default=0, help_text='Orden en que aparece en la UI', verbose_name='orden visual')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_trabajo_detalle', to='administracion_acceso_configuracion.empresa', verbose_name='empresa')),
                ('mecanico_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_asignados', to=settings.AUTH_USER_MODEL, verbose_name='mecánico asignado')),
                ('orden_global', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='atencion_tecnica_ejecucion.ordentrabajoglobal', verbose_name='orden de trabajo global')),
                ('plan_detalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_detalles', to='vehiculos_servicios_plan_citas.planserviciodetalle', verbose_name='detalle del plan')),
                ('servicio_catalogo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_trabajo_detalles', to='vehiculos_servicios_plan_citas.serviciocatalogo', verbose_name='servicio catálogo')),
            ],
            options={
                'verbose_name': 'Detalle Orden Trabajo',
                'verbose_name_plural': 'Detalles Órdenes Trabajo',
                'db_table': 'ordenes_trabajo_detalle',
                'ordering': ['orden_global', 'orden_visual'],
            },
        ),
        migrations.CreateModel(
            name='AvanceVehiculo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('GENERAL', 'General'), ('SERVICIO', 'Servicio específico')], max_length=20, verbose_name='tipo')),
                ('estado_nuevo', models.CharField(help_text='Estado al que pasó (ej: En espera de piezas)', max_length=100, verbose_name='estado nuevo')),
                ('mensaje', models.CharField(help_text='Mensaje a mostrar al cliente', max_length=500, verbose_name='mensaje')),
                ('porcentaje_avance', models.IntegerField(blank=True, help_text='Porcentaje de avance (0-100)', null=True, verbose_name='porcentaje de avance')),
                ('visible_cliente', models.BooleanField(default=True, verbose_name='visible para cliente')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avances', to='vehiculos_servicios_plan_citas.cita', verbose_name='cita')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avances_vehiculo', to='administracion_acceso_configuracion.empresa', verbose_name='empresa')),
                ('orden_detalle', models.ForeignKey(blank=True, help_text='Si es avance de servicio específico', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avances', to='atencion_tecnica_ejecucion.ordentrabajodetalle', verbose_name='detalle orden trabajo')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avances_registrados', to=settings.AUTH_USER_MODEL, verbose_name='registrado por')),
            ],
            options={
                'verbose_name': 'Avance Vehículo',
                'verbose_name_plural': 'Avances Vehículo',
                'db_table': 'avances_vehiculo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecepcionVehiculo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_recepcion', models.DateTimeField(auto_now_add=True, help_text='Fecha/hora cuando se registra la recepción', verbose_name='fecha de recepción')),
                ('kilometraje_ingreso', models.IntegerField(help_text='Kilómetros del vehículo al ingresar', verbose_name='kilometraje de ingreso')),
                ('nivel_combustible', models.CharField(choices=[('1/4', '1/4 de tanque'), ('1/2', '1/2 de tanque'), ('3/4', '3/4 de tanque'), ('LLENO', 'Lleno')], default='1/2', max_length=20, verbose_name='nivel de combustible')),
                ('observaciones', models.TextField(blank=True, help_text='Notas adicionales sobre la recepción', null=True, verbose_name='observaciones adicionales')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('asesor_registra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recepciones_registradas', to=settings.AUTH_USER_MODEL, verbose_name='asesor que registra')),
                ('cita', models.OneToOneField(help_text='Una recepción por cita', on_delete=django.db.models.deletion.CASCADE, related_name='recepcion', to='vehiculos_servicios_plan_citas.cita', verbose_name='cita')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recepciones_vehiculo', to='administracion_acceso_configuracion.empresa', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'Recepción Vehículo',
                'verbose_name_plural': 'Recepciones Vehículos',
                'db_table': 'recepciones_vehiculo',
                'ordering': ['-fecha_recepcion'],
                'indexes': [models.Index(fields=['empresa', 'cita'], name='recepciones_empresa_97380b_idx'), models.Index(fields=['asesor_registra', '-fecha_recepcion'], name='recepciones_asesor__eb19cf_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='recepcionvehiculo',
            constraint=models.UniqueConstraint(fields=('empresa', 'cita'), name='uq_recepcion_empresa_cita'),
        ),
        migrations.AddIndex(
            model_name='ordentrabajoglobalmecanico',
            index=models.Index(fields=['orden_global', 'mecanico'], name='ordenes_tra_orden_g_da25bd_idx'),
        ),
        migrations.AddIndex(
            model_name='ordentrabajoglobal',
            index=models.Index(fields=['empresa', 'estado'], name='ordenes_tra_empresa_269412_idx'),
        ),
        migrations.AddConstraint(
            model_name='ordentrabajoglobal',
            constraint=models.UniqueConstraint(fields=('empresa', 'numero'), name='unique_empresa_numero_orden'),
        ),
        migrations.AddIndex(
            model_name='ordentrabajodetalle',
            index=models.Index(fields=['orden_global', 'estado'], name='ordenes_tra_orden_g_2b1db0_idx'),
        ),
        migrations.AddIndex(
            model_name='ordentrabajodetalle',
            index=models.Index(fields=['mecanico_asignado'], name='ordenes_tra_mecanic_0b4574_idx'),
        ),
        migrations.AddIndex(
            model_name='avancevehiculo',
            index=models.Index(fields=['cita', '-created_at'], name='avances_veh_cita_id_76491b_idx'),
        ),
    ]
