# Generated by Django 4.2.8 on 2026-05-08 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('atencion_tecnica_ejecucion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepcionvehiculo',
            name='fecha_recogida',
            field=models.DateTimeField(blank=True, help_text='Fecha/hora cuando el cliente recogió el vehículo', null=True, verbose_name='fecha de recogida'),
        ),
        migrations.AddField(
            model_name='recepcionvehiculo',
            name='recogido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recepciones_recogidas', to=settings.AUTH_USER_MODEL, verbose_name='recogido por'),
        ),
    ]
