# Generated by Django 4.2.8 on 2026-05-26 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("administracion_acceso_configuracion", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auditoria",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Auditoría",
                "verbose_name_plural": "Auditorías",
            },
        ),
        migrations.AlterModelOptions(
            name="suscripcion",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Suscripción",
                "verbose_name_plural": "Suscripciones",
            },
        ),
        migrations.AlterField(
            model_name="auditoria",
            name="accion",
            field=models.CharField(
                db_index=True,
                help_text="Tipo de acción (crear, actualizar, eliminar, login, etc)",
                max_length=100,
                verbose_name="acción",
            ),
        ),
        migrations.AlterField(
            model_name="auditoria",
            name="descripcion",
            field=models.CharField(
                blank=True,
                help_text="Descripción legible de la acción",
                max_length=500,
                null=True,
                verbose_name="descripción",
            ),
        ),
        migrations.AlterField(
            model_name="auditoria",
            name="entidad_tipo",
            field=models.CharField(
                blank=True,
                help_text="Modelo sobre el que se actuó (Usuario, Empresa, etc)",
                max_length=100,
                null=True,
                verbose_name="tipo de entidad",
            ),
        ),
        migrations.AlterField(
            model_name="auditoria",
            name="ip",
            field=models.GenericIPAddressField(
                blank=True,
                help_text="IP desde donde se realizó la acción",
                null=True,
                verbose_name="IP",
            ),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="slug",
            field=models.CharField(
                db_index=True,
                help_text="Identificador único para URL (ej: acme, globex)",
                max_length=255,
                unique=True,
                verbose_name="slug",
            ),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="stripe_customer_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="ID del customer en Stripe para facturación",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Stripe Customer ID",
            ),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="suscripcion_hasta",
            field=models.DateTimeField(
                blank=True,
                help_text="Fecha de vencimiento de la suscripción actual",
                null=True,
                verbose_name="suscripción hasta",
            ),
        ),
        migrations.AlterField(
            model_name="pago",
            name="moneda",
            field=models.CharField(
                default="USD",
                help_text="Código de moneda ISO (USD, EUR, CLP)",
                max_length=3,
                verbose_name="moneda",
            ),
        ),
        migrations.AlterField(
            model_name="pago",
            name="processed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Cuándo se procesó el pago exitosamente",
                null=True,
                verbose_name="procesado en",
            ),
        ),
        migrations.AlterField(
            model_name="pago",
            name="usuario_password",
            field=models.CharField(
                blank=True,
                help_text="Password sin hashar (se hasheará al crear el usuario)",
                max_length=255,
                null=True,
                verbose_name="password del usuario",
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="codigo",
            field=models.CharField(
                db_index=True,
                help_text="Código único del plan (ej: STARTER, PRO, ENTERPRISE)",
                max_length=100,
                unique=True,
                verbose_name="código",
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="descripcion",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="descripción"
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="duracion_dias",
            field=models.IntegerField(
                help_text="Período de facturación en días (30, 365, etc)",
                verbose_name="duración (días)",
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="moneda",
            field=models.CharField(
                default="USD",
                help_text="Código de moneda ISO (USD, EUR, CLP)",
                max_length=3,
                verbose_name="moneda",
            ),
        ),
        migrations.AlterField(
            model_name="rol",
            name="descripcion",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="descripción"
            ),
        ),
        migrations.AlterField(
            model_name="suscripcion",
            name="fecha_aplicacion_plan_pendiente",
            field=models.DateTimeField(
                blank=True,
                help_text="Fecha exacta en la que el plan pendiente pasa a ser el plan actual",
                null=True,
                verbose_name="fecha de aplicación del plan pendiente",
            ),
        ),
        migrations.AlterField(
            model_name="suscripcion",
            name="notas",
            field=models.CharField(
                blank=True,
                help_text="Notas internas sobre la suscripción",
                max_length=500,
                null=True,
                verbose_name="notas",
            ),
        ),
        migrations.AlterField(
            model_name="suscripcion",
            name="pago_plan_pendiente",
            field=models.OneToOneField(
                blank=True,
                help_text="Referencia AL REGISTRO ACTUAL del pago confirmado para el cambio pendiente. Este es un VINCULO al pago actualmente asociado con plan_pendiente. El historial completo de todos los pagos permanece en la tabla Pago (nunca se eliminan). Cuando se aplica el plan_pendiente automáticamente, este campo se limpia (SET_NULL). Un solo pago confirmado puede estar vinculado a la vez.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="suscripcion_plan_pendiente",
                to="administracion_acceso_configuracion.pago",
                verbose_name="pago del plan pendiente",
            ),
        ),
        migrations.AlterField(
            model_name="suscripcion",
            name="plan_pendiente",
            field=models.ForeignKey(
                blank=True,
                help_text="Plan que se aplicará después de terminar el período actual",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="suscripciones_pendiente",
                to="administracion_acceso_configuracion.plan",
                verbose_name="plan pendiente",
            ),
        ),
        migrations.AlterField(
            model_name="suscripcion",
            name="renovacion_de",
            field=models.ForeignKey(
                blank=True,
                help_text="Si es renovación, referencia a la suscripción anterior",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="renovaciones",
                to="administracion_acceso_configuracion.suscripcion",
                verbose_name="renovación de",
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="email",
            field=models.EmailField(
                db_index=True,
                help_text="Email único dentro de la empresa (no bloqueado globalmente)",
                max_length=255,
                verbose_name="email",
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Designa si el usuario puede iniciar sesión",
                verbose_name="activo",
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="noti_email",
            field=models.BooleanField(
                default=True,
                help_text="Indica si el usuario desea recibir notificaciones por email",
                verbose_name="notificación por email",
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="noti_push",
            field=models.BooleanField(
                default=True,
                help_text="Indica si el usuario desea recibir notificaciones push",
                verbose_name="notificación push",
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="session_revoked_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Si está seteado, todos los tokens emitidos antes de esta fecha son inválidos",
                null=True,
                verbose_name="sesión revocada en",
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="telefono",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="teléfono"
            ),
        ),
    ]
